import requests
import pandas as pd

def fetch_hyderabad_complete_history():
    # Target geographical coordinates (City Center Baseline)
    lat, lon = 17.3850, 78.4867
    start_date = "2026-01-13"
    end_date = "2026-07-13"
    
    print("📡 Initializing connection to Open-Meteo Unified Archives...")
    
    # 1. Retrieve Historical Atmospheric Weather Parameters
    weather_url = (
        f"https://archive-api.open-meteo.com/v1/archive?"
        f"latitude={lat}&longitude={lon}&start_date={start_date}&end_date={end_date}"
        f"&hourly=temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m,wind_direction_10m"
        f"&timezone=Asia%2FKolkata"
    )
    
    print("⏳ Downloading hourly meteorological telemetry data...")
    weather_response = requests.get(weather_url)
    if weather_response.status_code != 200:
        print("❌ Weather Archive API Error:", weather_response.text)
        return
        
    w_data = weather_response.json()
    weather_df = pd.DataFrame({
        "timestamp": w_data["hourly"]["time"],
        "temperature_c": w_data["hourly"]["temperature_2m"],
        "humidity_percent": w_data["hourly"]["relative_humidity_2m"],
        "pressure_hpa": w_data["hourly"]["surface_pressure"],
        "wind_speed_m_s": w_data["hourly"]["wind_speed_10m"],
        "wind_direction_deg": w_data["hourly"]["wind_direction_10m"]
    })

    # 2. Retrieve Historical Air Quality Records (CAMS Archive)
    aqi_url = (
        f"https://air-quality-api.open-meteo.com/v1/air-quality?"
        f"latitude={lat}&longitude={lon}&start_date={start_date}&end_date={end_date}"
        f"&hourly=european_aqi"
        f"&timezone=Asia%2FKolkata"
    )
    
    print("⏳ Downloading historical atmospheric air quality metrics...")
    aqi_response = requests.get(aqi_url)
    if aqi_response.status_code != 200:
        print("❌ Air Quality Archive API Error:", aqi_response.text)
        return
        
    a_data = aqi_response.json()
    aqi_df = pd.DataFrame({
        "timestamp": a_data["hourly"]["time"],
        "target_aqi": a_data["hourly"]["european_aqi"]
    })

    # 3. Synchronize Datasets chronologically
    print("⚙️ Processing structural merge across timestamp index...")
    merged_df = pd.merge(weather_df, aqi_df, on="timestamp", how="inner")
    
    # Clean up null/missing rows generated by archival gaps
    merged_df = merged_df.dropna()
    
    # 4. Commit to storage pipeline
    output_path = r"D:\ET Hackathon\data\hyderabad_6month_history.csv"
    merged_df.to_csv(output_path, index=False)
    
    print(f"\n✅ SUCCESS: Compiled {len(merged_df)} hours of authentic, weather-aligned metrics.")
    print(f"📁 Dataset written directly to: {output_path}")

if __name__ == "__main__":
    fetch_hyderabad_complete_history()